apiVersion: v1
kind: ReplicationController
metadata:
  name: asterisk
spec:
  replicas: 2
  selector:
    app: asterisk
  template:
    metadata:
      name: asterisk
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: asterisk-discovery
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        imagePullPolicy: Never