apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
    tier: backend
spec:
  ports:
  - port: 2379
  selector:
    app: etcd
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
        tier: backend
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 2379
        command: ["etcd"]
        args: [
          "-listen-client-urls", 
          "http://0.0.0.0:2379", 
          "-advertise-client-urls",
          "http://0.0.0.0:2379"
        ]
